// DEV/SEED ONLY: Remote demo image URLs below are for admin seed tooling.
// They are not used as production UI fallbacks when a listing has no photo.
export const seedListings = [
  {
    title: 'Toyota Hilux 2.8 D-4D 4x4 otomatik',
    category: 'Araç',
    subcategory: 'Pickup',
    price: 3650000,
    location: 'Nouméa',
    condition: 'used',
    seller_name: 'NC Auto Pro',
    seller_phone: '+687 77 42 18',
    seller_email: 'auto@noumarket.nc',
    description: 'Bakımlı 4x4 Hilux. Otomatik vites, klima, geri görüş kamerası, servis geçmişi mevcut. Nouméa içinde görülebilir.',
    image_url: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80',
    is_featured: true,
    view_count: 812,
    metadata: { brand: 'Toyota', model: 'Hilux', year: 2019, mileage: 86000, fuel: 'Dizel', transmission: 'Otomatik' },
  },
  {
    title: 'Dumbéa’da aileye uygun 3 odalı ev',
    category: 'Emlak',
    subcategory: 'Satılık Ev',
    price: 38500000,
    location: 'Dumbéa',
    condition: 'used',
    seller_name: 'Île Immo',
    seller_phone: '+687 91 30 24',
    seller_email: 'immo@noumarket.nc',
    description: 'Sessiz bölgede bahçeli 3 odalı ev. Otopark, teras ve geniş salon. Aile yaşamı için güçlü seçenek.',
    image_url: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1200&q=80',
    is_featured: true,
    view_count: 641,
    metadata: { rooms: 4, bedrooms: 3, area_m2: 118, property_type: 'Ev', transaction: 'Satılık' },
  },
  {
    title: 'Anse Vata denize yakın eşyalı stüdyo',
    category: 'Emlak',
    subcategory: 'Kiralık Daire',
    price: 125000,
    location: 'Anse Vata',
    condition: 'used',
    seller_name: 'Julie Martin',
    seller_phone: '+687 83 16 75',
    seller_email: 'julie@noumarket.nc',
    description: 'Denize 5 dakika yürüyüş mesafesinde, eşyalı, temiz stüdyo. Tek kişi veya çift için uygun.',
    image_url: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80',
    is_featured: false,
    view_count: 452,
    metadata: { rooms: 1, area_m2: 32, furnished: true, transaction: 'Kiralık' },
  },
  {
    title: 'iPhone 14 Pro 256 GB kutulu',
    category: 'Elektronik',
    subcategory: 'Telefon',
    price: 98000,
    location: 'Nouméa Centre',
    condition: 'used',
    seller_name: 'Thomas L.',
    seller_phone: '+687 78 91 05',
    seller_email: 'thomas@noumarket.nc',
    description: 'Kutusuyla beraber, pil sağlığı iyi, ekran temiz. Face ID sorunsuz çalışıyor.',
    image_url: 'https://images.unsplash.com/photo-1663499482523-1c0c1bae4ce1?auto=format&fit=crop&w=1200&q=80',
    is_featured: true,
    view_count: 388,
    metadata: { brand: 'Apple', model: 'iPhone 14 Pro', storage: '256 GB', warranty: 'Yok' },
  },
  {
    title: 'MacBook Air M2 13 inch 16GB RAM',
    category: 'Elektronik',
    subcategory: 'Bilgisayar',
    price: 145000,
    location: 'Nouméa',
    condition: 'used',
    seller_name: 'Sophie Tech',
    seller_phone: '+687 74 20 11',
    seller_email: 'sophie@noumarket.nc',
    description: 'Temiz kullanılmış MacBook Air M2. 16GB RAM, 512GB SSD. Şarj döngüsü düşük.',
    image_url: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=80',
    is_featured: false,
    view_count: 267,
    metadata: { brand: 'Apple', processor: 'M2', ram: '16 GB', storage: '512 GB SSD' },
  },
  {
    title: 'Yamaha 15HP dıştan takma tekne motoru',
    category: 'Denizcilik',
    subcategory: 'Tekne Motoru',
    price: 220000,
    location: 'Mont-Dore',
    condition: 'used',
    seller_name: 'Lagoon Marine',
    seller_phone: '+687 86 55 42',
    seller_email: 'marine@noumarket.nc',
    description: 'Bakımları yapılmış Yamaha 15HP motor. Balıkçılık ve küçük tekne için ideal.',
    image_url: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80',
    is_featured: true,
    view_count: 531,
    metadata: { brand: 'Yamaha', power_hp: 15, engine_type: 'Outboard', service_history: true },
  },
  {
    title: 'Kite surf ekipman seti',
    category: 'Spor & Hobi',
    subcategory: 'Su Sporları',
    price: 85000,
    location: 'Anse Vata',
    condition: 'used',
    seller_name: 'Kite NC',
    seller_phone: '+687 75 61 90',
    seller_email: 'kite@noumarket.nc',
    description: 'Board, kite ve harness dahil başlangıç/orta seviye set. Fotoğraftaki ekipmanlar dahildir.',
    image_url: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&w=1200&q=80',
    is_featured: false,
    view_count: 198,
    metadata: { sport: 'Kitesurf', level: 'Beginner/Intermediate' },
  },
  {
    title: 'Samsung buzdolabı No Frost',
    category: 'Ev & Yaşam',
    subcategory: 'Beyaz Eşya',
    price: 55000,
    location: 'Dumbéa',
    condition: 'used',
    seller_name: 'Claire B.',
    seller_phone: '+687 79 44 12',
    seller_email: 'claire@noumarket.nc',
    description: 'Taşınma sebebiyle satılık. No Frost, geniş hacimli, temiz kullanılmış.',
    image_url: 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=1200&q=80',
    is_featured: false,
    view_count: 143,
    metadata: { brand: 'Samsung', type: 'No Frost', delivery: 'Alıcı teslim alır' },
  },
  {
    title: 'Temizlik hizmeti - ev/ofis',
    category: 'Hizmet',
    subcategory: 'Temizlik',
    price: 3500,
    location: 'Nouméa',
    condition: 'new',
    seller_name: 'Clean NC Services',
    seller_phone: '+687 72 10 88',
    seller_email: 'clean@noumarket.nc',
    description: 'Ev ve ofis temizliği. Saatlik veya düzenli anlaşma yapılır. Nouméa ve çevresi.',
    image_url: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1200&q=80',
    is_featured: true,
    view_count: 321,
    metadata: { service_area: 'Nouméa, Dumbéa', unit: 'saatlik' },
  },
  {
    title: 'Renault Clio düşük kilometre',
    category: 'Araç',
    subcategory: 'Otomobil',
    price: 1450000,
    location: 'Païta',
    condition: 'used',
    seller_name: 'Auto Païta',
    seller_phone: '+687 81 24 17',
    seller_email: 'paita@noumarket.nc',
    description: 'Ekonomik şehir aracı. Klima, Bluetooth, düzenli bakım. Yeni muayene.',
    image_url: 'https://images.unsplash.com/photo-1549924231-f129b911e442?auto=format&fit=crop&w=1200&q=80',
    is_featured: false,
    view_count: 289,
    metadata: { brand: 'Renault', model: 'Clio', year: 2018, mileage: 54000, fuel: 'Benzin' },
  },
  {
    title: 'Ofis için masa sandalye takımı',
    category: 'Ev & Yaşam',
    subcategory: 'Mobilya',
    price: 32000,
    location: 'Nouméa Centre',
    condition: 'used',
    seller_name: 'Bureau NC',
    seller_phone: '+687 73 62 09',
    seller_email: 'office@noumarket.nc',
    description: '2 masa, 4 sandalye. Ofis kapanışı nedeniyle uygun fiyatlı toplu satış.',
    image_url: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80',
    is_featured: false,
    view_count: 176,
    metadata: { pieces: 6, material: 'Ahşap/metal' },
  },
  {
    title: 'Bateau aluminium 5m balıkçı teknesi',
    category: 'Denizcilik',
    subcategory: 'Tekne',
    price: 890000,
    location: 'La Foa',
    condition: 'used',
    seller_name: 'Pierre Marine',
    seller_phone: '+687 84 33 50',
    seller_email: 'pierre@noumarket.nc',
    description: 'Alüminyum 5 metre balıkçı teknesi. Römork dahil. Motor ayrı görüşülür.',
    image_url: 'https://images.unsplash.com/photo-1528154291023-a6525fabe5b4?auto=format&fit=crop&w=1200&q=80',
    is_featured: true,
    view_count: 474,
    metadata: { length_m: 5, material: 'Aluminium', trailer: true },
  },
];
